# render.yaml
services:
    - type: static
      name: NhaHangChaySen_FE # Đặt tên dịch vụ chính xác như trên Render
      rootDir: . # Thư mục gốc của repository (nơi file render.yaml này nằm)
      buildCommand: npm install && npm run build
      staticPublishPath: dist # Thư mục chứa các file đã build của Vite
      pullRequestPreviewsEnabled: true
      redirects:
          - source: /*
            destination: /index.html
            type: rewrite
